### ISSUE TITLE
Adding Links takes a very long time

### ISSUE THREAD

**Issue by R-A-R-E** [Cr1TiKa7/My.Jdownloader.Api#11]
Its taking around 10-20 Seconds to add 1 UJ

https://i.gyazo.com/088bfe7029baf9d6401ef287bf418cdd.png

**Comment by Cr1TiKa7** [comment]
That could be an issue because of the route of the api/library. It first sends the request to the jdownloader api and the jdownloader api redirects it to your local client.

But you can set a second parameter to the GetDeviceHandler Function which allows you to connect to your local jdownloader client directly without going to the jdownloader api first.

**Comment by R-A-R-E** [comment]
Also sometimes when it adds to jdownloader from real-debrid it changes the name to n
