### ISSUE TITLE
Documentation is outdated

### ISSUE THREAD

**Issue by JPBotelho** [Cr1TiKa7/My.Jdownloader.Api#2]
JDownloaderHandler() requires an appkey, and that is not stated in the readme. I used my login email and it worked fine.

**Comment by Cr1TiKa7** [comment]
Thank you for reporting this issue!

I wouldn't recommend to use your own email as the appkey. Instead I would recommend you to use a guid because it should always be unique. 

Also if you are planning to write multiple applications then you should also use different appkeys. The JDownloader Api could otherwise block access for a while if you send too many requests within a small timespan.
