### ISSUE TITLE
[Question] - How to add a 'comment' to a Package? Missing method from JDownload docs or this API?

### ISSUE THREAD

**Issue by jeffward01** [Cr1TiKa7/My.Jdownloader.Api#9]
Hello!

I have been looking everywhere for this, and I can't seem to find how we can add 'comments' to packages via the API.

I see this [support issue on JDownloader](https://board.jdownloader.org/showthread.php?t=90638) that explains how to do it, but it appears the methods are missing.

> @mrdial8: I will add a --> (from moderator user: Jiaz)

`setComment(long[] linkIds, long[] packageIds,boolean setPackageChildren, String comment)`

> api method in downloadsV2 and linkgrabberv2 namespace
comment will only be set on specified links/packages if setPackageChildren=false
else it will auto apply comment to all package children, so you don't have to specify them all
> 
> In case you need method to be different or other/more methods, please just let us know! -> (from moderator user: Jiaz)

However, when I look on the [JDownload API Docs](https://my.jdownloader.org/developers/) - I do not see the `setcomment()` method Jiaz was talking about.

Is this a question for JDownloader admins, or for the [My.Jdownloader.API](https://github.com/Cr1TiKa7/My.Jdownloader.Ap)?

This library is GREAT!! Thank you!

**Comment by Cr1TiKa7** [comment]
Hello!

As far as I can see from the post you've linked this call was just added in the may update but their api documentation was not updated. 

I've added the call for the DownloadsV2 and LinkgrabberV2 namespace. It works for the DownloadsV2 namespace but for some reason it's not working on the LinkgrabberV2 namespace and I can't figure out why since the return value is always:
`
{
 "data"     : "",
 "diffID"   : null,
 "diffType" : null,
 "rid"      : -1
}
`
So there is no indication on what went wrong :/

But i've implemented it already in case it gets fixed in the future!
2.4.5 is on it's way to the nuget repository :)
Thank you very much!

**Comment by jeffward01** [comment]
Big thank you!! You are really awesome, you go above and beyond. I am also a C# developer, I feel sheepish that your doing so much work on this great repository!

Is there anything I can help with?
